-- Run this in Supabase SQL Editor.
create table public.transactions (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('income','expense')),
  date date not null,
  category text not null,
  party text not null,
  amount numeric(12,2) not null check (amount >= 0),
  note text,
  entered_by text,
  created_at timestamptz not null default now()
);

alter table public.transactions enable row level security;

-- Soft-login version: shared read/write access.
-- The app itself controls which UI is shown to editors.
create policy "public read transactions"
on public.transactions for select
to anon, authenticated
using (true);

create policy "public insert transactions"
on public.transactions for insert
to anon, authenticated
with check (true);

create policy "public delete transactions"
on public.transactions for delete
to anon, authenticated
using (true);

-- IMPORTANT:
-- This is intentionally simple and uses a soft editor PIN in the frontend.
-- Anyone who can inspect the website source can discover the PIN.
-- For stronger protection, switch to Supabase Auth + editor role policies later.
